package com.rubify.pinyin

import android.content.res.AssetManager

/** Loads the dictionary generated by tools/pinyin-data from `assets/pinyin`. */
object PinyinAssets {
    fun load(assets: AssetManager): PinyinDictionary =
        assets.open("pinyin/chars.tsv").bufferedReader().use { chars ->
            assets.open("pinyin/words.tsv").bufferedReader().use { words ->
                PinyinDictionary.load(chars, words)
            }
        }
}
